export default {
    genders: [
        { text: 'Male', value: 'M' },
        { text: 'Female', value: 'F' }
    ],
    degrees: [
        'High School (SMA, SMK, etc)',
        'Diploma Degree (D3)',
        'Bachelor Degree (S1, D4)',
        'Master Degree',
        'Doctorate'
    ],
    fieldOfStudies: [
        'Advertising / Media', 
        'Agriculture / Aquaculture / Forestry',
        'Airline Operation / Airline Management',
        'Architecture',
        'Art / Design / Creative Multimedia',
        'Biology',
        'Biotechnology',
        'Business Studies / Administration Management',
        'Chemistry',
        'Commerce',
        'Computer Science / Information Technology',
        'Dentistry',
        'Economics',
        'Journalism',
        'Education / Teaching / Training',
        'Engineering: Aviation / Aeronautics / Astronautics',
        'Engineering: Bioengineering / Biomedical',
        'Engineering: Chemical',
        'Engineering: Civil',
        'Engineering: Computer / Telecommunication',
        'Engineering: Electrical / Electronic',
        'Engineering: Industrial',
        'Engineering: Marine',
        'Engineering: Material Science',
        'Engineering: Mechanical',
        'Engineering: Mechatronics / Electromechanical',
        'Engineering: Metal Fabrication / Tool & Die / Welding',
        'Engineering: Mining / Mineral',
        'Engineering: Others',
        'Engineering: Petroleum / Oil / Gas',
        'Finance / Accountantcy / Banking',
        'Food & Beverage Service Management',
        'Food Technology / Nutrition / Dietetics',
        'Geographical Science',
        'Geology / Geophysics',
        'History',
        'Hospitality / Tourism / Hotel Management',
        'Human Resource Management',
        'Humanities / Liberal Arts',
        'Logistics / Transporation',
        'Law',
        'Library Management',
        'Linguistics / Languages',
        'Mass Communication',
        'Mathematics',
        'Medical Science',
        'Medicine',
        'Maritime Studies',
        'Marketing',
        'Music / Performing Arts Studies',
        'Nursing',
        'Optometry',
        'Personal Services',
        'Pharmacy / Pharmacology',
        'Philosophy',
        'Physical Therapy / Physiotherapy',
        'Physics',
        'Political Science',
        'Property Development / Real Estate Management',
        'Protective Services & Management',
        'Psychology',
        'Quantity Survey',
        'Science & Technology',
        'Secretarial',
        'Social Science / Sociology',
        'Sports Science & Management',
        'Textile / Fashion Design',
        'Urban Studies / Town Planning',
        'Veterinary',
        'Others'
    ],
    companyIndustry: [
        'Accounting',
        'Advertising / Marketing / PR',
        'Airlines / Aviation',
        'Agricultural / Poultry / Plantation / Fishery',
        'Alternative Dispute Resolution',
        'Alternative Medicine',
        'Animation',
        'Apparel & Fashion',
        'Architecture & Planning',
        'Architectural Service / Design Service',
        'Arts and Crafts',
        'Automotive',
        'Aviation & Aerospace',
        'Banking',
        'Biotechnology',
        'Broadcast Media',
        'Building Materials',
        'Business Supply & Equipment',
        'Capital Market',
        'Call Center / IT Enabled Service',
        'Chemical',
        'Civic & Social Organization',
        'Civil Engineering',
        'Commercial Real Estate',
        'Computer & Network Security',
        'Computer Games',
        'Computer Hardware',
        'Computer Networking',
        'Computer Software',
        'Construction',
        'Consumer Electronics',
        'Consulting: Business & Management',
        'Consulting: IT, Science, Engineering and Technical',
        'Consumer Goods',
        'Customer Service',
        'Cosmetics',
        'Dairy',
        'Defense & Space',
        'Design',
        'Education Management',
        'E-Learning',
        'Electrical / Electronic Manufacturing',
        'Entertainment',
        'Environmental Service',
        'Events Service',
        'Food Production',
        'Fund-raising',
        'Furniture',
        'Fast Moving Consumer Goods',
        'Gambling & Casinos',
        'Gems / Jewelry',
        'Glass / Ceramic / Concrete',
        'Government Administration',
        'Government Relation',
        'Graphic Design',
        'Grooming / Beauty / Lifestyle',
        'Health / Wellness / Fitness',
        'Heavy Industrial / Machineries',
        'Higher Education',
        'Hospital & Health Care',
        'Hospitality',
        'Human Resources',
        'HR Management & Consulting',
        'Import & Export',
        'Individual & Family Service',
        'Industrial Automation',
        'Information Services',
        'Information Technology & Services',
        'Insurance',
        'International Affairs',
        'International Trade & Development',
        'Internet',
        'Investment Banking',
        'Invistment Management',
        'Judiciary',
        'Journalism',
        'Law Enforcement',
        'Law Practice',
        'Legal Service',
        'Legislative Office',
        'Leisure, Travel & Tourism',
        'Libraries',
        'Logistics & Supply Chain',
        'Luxury Goods & Jewelry',
        'Machinery',
        'Management Consulting',
        'Manufacture / Production',
        'Maritime',
        'Marketing & Advertising',
        'Market Research',
        'Mechanical / Industrial Engineering',
        'Media Production',
        'Medical Devices',
        'Medical Practice',
        'Mental Health Care',
        'Military',
        'Mining & Metals',
        'Motion Pictures & Film',
        'Museum & Institutions',
        'Music',
        'Nanotechnology',
        'Non Government Organization',
        'Newspaper',
        'Nonprofit Organization Management',
        'Oil, Gas & Energy',
        'Online Media',
        'Outsourcing / Offshoring',
        'Package / Freight Delivery',
        'Packaging & Container',
        'Paper & Forest Product',
        'Performing Arts',
        'Pharmaceuticals',
        'Philantrophy',
        'Photography',
        'Plastic',
        'Political Organization',
        'Primary / Secondary Education',
        'Printing',
        'Professional Training & Coaching',
        'Program Development',
        'Public Policy',
        'Public Relations & Communications',
        'Public Safety',
        'Publishing',
        'Railroad Manufacture',
        'Ranching',
        'Real Estate',
        'Repair / Maintenance Service',
        'Recreational Facilities & Services',
        'Religious Institution',
        'Renewables & Environment',
        'Research',
        'Restaurant',
        'Retail',
        'Science / Technology',
        'Security & Investigation',
        'Semiconductors',
        'Shipbuilding',
        'Sporting Goods',
        'Sports',
        'Staffing & Recruiting',
        'Supermarkets',
        'Stock / Securities',
        'Telecommunication',
        'Textiles',
        'Think Tanks',
        'Tobacco',
        'Translation & Localizations',
        'Transportation / Trucking / Railroad',
        'Utilities',
        'Venture Capital & Private Equity',
        'Veterinary',
        'Warehousing',
        'Wholesale',
        'Wine & Spirits',
        'Wireless',
        'Writing & Editing',
        'Others'
    ],
    jobFunction: [
        'Accounting / Auditing',
        'Administrative',
        'Advertising',
        'Business Analyst',
        'Financial Analyst',
        'Data Analyst',
        'Art / Creative',
        'Business Development',
        'Consulting',
        'Customer Service',
        'Distribution',
        'Design',
        'Education',
        'Engineering',
        'Finance',
        'General Business',
        'Health Care Provider',
        'Human Resources',
        'Information Technology',
        'Legal',
        'Management',
        'Manufacturing',
        'Marketing',
        'Public Relation',
        'Purchasing',
        'Product Management',
        'Project Management',
        'Production',
        'Quality Assurance',
        'Research',
        'Sales',
        'Science',
        'Strategy / Planning',
        'Supply Chain',
        'Training',
        'Writing / Editing',
        'Others'
    ],
    levelOfExperience: [
        'Fresh graduates / Less than 1 year experience',
        'Staff / Junior staff',
        'Senior staff / Supervisor / Coordinator / Team leader',
        'Manager / Senior manager / Department head',
        'Associate director / Director / General manager',
        'C level (CEO, CFO, CTO, COO, CMO)',
        'Others'
    ],
}