export default {
    genders: [
        { text: 'Male', value: 'M' },
        { text: 'Female', value: 'F' }
    ],
    degrees: [
        'High School (SMA, SMK, etc)',
        'Diploma Degree (D3)',
        'Bachelor Degree (S1, D4)',
        'Master Degree',
        'Doctorate'
    ],
    fieldOfStudies: [
        'Advertising / Media', 
        'Agriculture / Aquaculture / Forestry',
        'Airline Operation / Airline Management',
        'Architecture',
        'Art / Design / Creative Multimedia',
        'Biology',
        'Biotechnology',
        'Business Studies / Administration Management',
        'Chemistry',
        'Commerce',
        'Computer Science / Information Technology',
        'Dentistry',
        'Economics',
        'Journalism',
        'Education / Teaching / Training',
        'Engineering: Aviation / Aeronautics / Astronautics',
        'Engineering: Bioengineering / Biomedical',
        'Engineering: Chemical',
        'Engineering: Civil',
        'Engineering: Computer / Telecommunication',
        'Engineering: Electrical / Electronic',
        'Engineering: Industrial',
        'Engineering: Marine',
        'Engineering: Material Science',
        'Engineering: Mechanical',
        'Engineering: Mechatronics / Electromechanical',
        'Engineering: Metal Fabrication / Tool & Die / Welding',
        'Engineering: Mining / Mineral',
        'Engineering: Others',
        'Engineering: Petroleum / Oil / Gas',
        'Finance / Accountantcy / Banking',
        'Food & Beverage Service Management',
        'Food Technology / Nutrition / Dietetics',
        'Geographical Science',
        'Geology / Geophysics',
        'History',
        'Hospitality / Tourism / Hotel Management',
        'Human Resource Management',
        'Humanities / Liberal Arts',
        'Logistics / Transporation',
        'Law',
        'Library Management',
        'Linguistics / Languages',
        'Mass Communication',
        'Mathematics',
        'Medical Science',
        'Medicine',
        'Maritime Studies',
        'Marketing',
        'Music / Performing Arts Studies',
        'Nursing',
        'Optometry',
        'Personal Services',
        'Pharmacy / Pharmacology',
        'Philosophy',
        'Physical Therapy / Physiotherapy',
        'Physics',
        'Political Science',
        'Property Development / Real Estate Management',
        'Protective Services & Management',
        'Psychology',
        'Quantity Survey',
        'Science & Technology',
        'Secretarial',
        'Social Science / Sociology',
        'Sports Science & Management',
        'Textile / Fashion Design',
        'Urban Studies / Town Planning',
        'Veterinary',
        'Others'
    ],
    companyIndustry: [
        'Accounting',
        'Advertising / Marketing / PR',
        'Airlines / Aviation',
        'Agricultural / Poultry / Plantation / Fishery',
        'Alternative Dispute Resolution',
        'Alternative Medicine',
        'Animation',
        'Apparel & Fashion',
        'Architecture & Planning',
        'Architectural Service / Design Service',
        'Arts and Crafts',
        'Automotive',
        'Aviation & Aerospace',
        'Banking',
        'Biotechnology',
        'Broadcast Media',
        'Building Materials',
        'Business Supply & Equipment',
        'Capital Market',
        'Call Center / IT Enabled Service',
        'Chemical',
        'Civic & Social Organization',
        'Civil Engineering',
        'Commercial Real Estate',
        'Computer & Network Security',
        'Computer Games',
        'Computer Hardware',
        'Computer Networking',
        'Computer Software',
        'Construction',
        'Consumer Electronics',
        'Consulting: Business & Management',
        'Consulting: IT, Science, Engineering and Technical',
        'Consumer Goods',
        'Customer Service',
        'Cosmetics',
        'Dairy',
        'Defense & Space',
        'Design',
        'Education Management',
        'E-Learning',
        'Electrical / Electronic Manufacturing',
        'Entertainment',
        'Environmental Service',
        'Events Service',
        'Food Production',
        'Fund-raising',
        'Furniture',
        'Fast Moving Consumer Goods',
        'Gambling & Casinos',
        'Gems / Jewelry',
        'Glass / Ceramic / Concrete',
        'Government Administration',
        'Government Relation',
        'Graphic Design',
        'Grooming / Beauty / Lifestyle',
        'Health / Wellness / Fitness',
        'Heavy Industrial / Machineries',
        'Higher Education',
        'Hospital & Health Care',
        'Hospitality',
        'Human Resources',
        'HR Management & Consulting',
        'Import & Export',
        'Individual & Family Service',
        'Industrial Automation',
        'Information Services',
        'Information Technology & Services',
        'Insurance',
        'International Affairs',
        'International Trade & Development',
        'Internet',
        'Investment Banking',
        'Invistment Management',
        'Judiciary',
        'Journalism',
        'Law Enforcement',
        'Law Practice',
        'Legal Service',
        'Legislative Office',
        'Leisure, Travel & Tourism',
        'Libraries',
        'Logistics & Supply Chain',
        'Luxury Goods & Jewelry',
        'Machinery',
        'Management Consulting',
        'Manufacture / Production',
        'Maritime',
        'Marketing & Advertising',
        'Market Research',
        'Mechanical / Industrial Engineering',
        'Media Production',
        'Medical Devices',
        'Medical Practice',
        'Mental Health Care',
        'Military',
        'Mining & Metals',
        'Motion Pictures & Film',
        'Museum & Institutions',
        'Music',
        'Nanotechnology',
        'Non Government Organization',
        'Newspaper',
        'Nonprofit Organization Management',
        'Oil, Gas & Energy',
        'Online Media',
        'Outsourcing / Offshoring',
        'Package / Freight Delivery',
        'Packaging & Container',
        'Paper & Forest Product',
        'Performing Arts',
        'Pharmaceuticals',
        'Philantrophy',
        'Photography',
        'Plastic',
        'Political Organization',
        'Primary / Secondary Education',
        'Printing',
        'Professional Training & Coaching',
        'Program Development',
        'Public Policy',
        'Public Relations & Communications',
        'Public Safety',
        'Publishing',
        'Railroad Manufacture',
        'Ranching',
        'Real Estate',
        'Repair / Maintenance Service',
        'Recreational Facilities & Services',
        'Religious Institution',
        'Renewables & Environment',
        'Research',
        'Restaurant',
        'Retail',
        'Science / Technology',
        'Security & Investigation',
        'Semiconductors',
        'Shipbuilding',
        'Sporting Goods',
        'Sports',
        'Staffing & Recruiting',
        'Supermarkets',
        'Stock / Securities',
        'Telecommunication',
        'Textiles',
        'Think Tanks',
        'Tobacco',
        'Translation & Localizations',
        'Transportation / Trucking / Railroad',
        'Utilities',
        'Venture Capital & Private Equity',
        'Veterinary',
        'Warehousing',
        'Wholesale',
        'Wine & Spirits',
        'Wireless',
        'Writing & Editing',
        'Others'
    ],
    jobFunction: [
        'Accounting / Auditing',
        'Administrative',
        'Advertising',
        'Business Analyst',
        'Financial Analyst',
        'Data Analyst',
        'Art / Creative',
        'Business Development',
        'Consulting',
        'Customer Service',
        'Distribution',
        'Design',
        'Education',
        'Engineering',
        'Finance',
        'General Business',
        'Health Care Provider',
        'Human Resources',
        'Information Technology',
        'Legal',
        'Management',
        'Manufacturing',
        'Marketing',
        'Public Relation',
        'Purchasing',
        'Product Management',
        'Project Management',
        'Production',
        'Quality Assurance',
        'Research',
        'Sales',
        'Science',
        'Strategy / Planning',
        'Supply Chain',
        'Training',
        'Writing / Editing',
        'Others'
    ],
    levelOfExperience: [
        'Fresh graduates / Less than 1 year experience',
        'Staff / Junior staff',
        'Senior staff / Supervisor / Coordinator / Team leader',
        'Manager / Senior manager / Department head',
        'Associate director / Director / General manager',
        'C level (CEO, CFO, CTO, COO, CMO)',
        'Others'
    ],
    provinces: [
        'Aceh', 
        'Bali', 
        'Banten', 
        'Bengkulu', 
        'DKI Yogyakarta', 
        'DKI Jakarta', 
        'Gorontalo', 
        'Jambi', 
        'Jawa Barat', 
        'Jawa Tengah', 
        'Jawa Timur', 
        'Kalimantan Barat', 
        'Kalimantan Selatan', 
        'Kalimantan Tengah', 
        'Kalimantan Timur', 
        'Kalimantan Utara', 
        'Kepulauan Bangka Belitung', 
        'Kepulauan Riau', 
        'Lampung', 
        'Maluku', 
        'Maluku Utara', 
        'Nusa Tenggara Barat', 
        'Nusa Tenggara Timur', 
        'Papua', 
        'Papua Barat', 
        'Riau', 
        'Sulawesi Barat', 
        'Sulawesi Selatan', 
        'Sulawesi Tengah', 
        'Sulawesi Tenggara', 
        'Sulawesi Utara', 
        'Sumatera Barat', 
        'Sumatera Selatan', 
        'Sumatera Utara'
    ],
    cities: [
        'Aceh Barat', 
        'Aceh Barat Daya', 
        'Aceh Besar', 
        'Aceh Jaya', 
        'Aceh Selatan', 
        'Aceh Singkil', 
        'Aceh Tamiang', 
        'Aceh Tengah', 
        'Aceh Tenggara', 
        'Aceh Timur', 
        'Aceh Utara', 
        'Agam', 
        'Alor', 
        'Ambon', 
        'Asahan', 
        'Asmat', 
        'Batam', 
        'Badung', 
        'Balangan', 
        'Balikpapan', 
        'Banda Aceh', 
        'Bandar Lampung', 
        'Bandung', 
        'Bandung Barat', 
        'Banggai', 
        'Banggai Kepulauan', 
        'Bangka', 
        'Bangka Barat', 
        'Bangka Selatan', 
        'Bangka Tengah', 
        'Bangkalan', 
        'Bangli', 
        'Banjar', 
        'Banjar Baru', 
        'Banjarmasin', 
        'Banjarnegara', 
        'Bantaeng', 
        'Bantul', 
        'Banyu Asin', 
        'Banyumas', 
        'Banyuwangi', 
        'Barito Kuala', 
        'Barito Selatan', 
        'Barito Timur', 
        'Barito Utara', 
        'Barru', 
        'Baru', 
        'Batang', 
        'Batang Hari', 
        'Batu', 
        'Batu Bara', 
        'Baubau', 
        'Bekasi', 
        'Belitung', 
        'Belitung Timur', 
        'Belu', 
        'Bener Meriah', 
        'Bengkalis', 
        'Bengkayang', 
        'Bengkulu', 
        'Bengkulu Selatan', 
        'Bengkulu Tengah', 
        'Bengkulu Utara', 
        'Berau', 
        'Biak Numfor', 
        'Bima', 
        'Binjai', 
        'Bintan', 
        'Bireuen', 
        'Bitung', 
        'Blitar', 
        'Blora', 
        'Boalemo', 
        'Bogor', 
        'Bojonegoro', 
        'Bolaang Mongondow', 
        'Bolaang Mongondow Selatan', 
        'Bolaang Mongondow Timur', 
        'Bolaang Mongondow Utara', 
        'Bombana', 
        'Bondowoso', 
        'Bone', 
        'Bone Bolango', 
        'Bontang', 
        'Boven Digoel', 
        'Boyolali', 
        'Brebes', 
        'Bukittinggi', 
        'Buleleng', 
        'Bulukumba', 
        'Bulungan', 
        'Bungo', 
        'Buol', 
        'Buru', 
        'Buru Selatan', 
        'Buton', 
        'Buton Utara', 
        'Ciamis', 
        'Cianjur', 
        'Cilacap', 
        'Cilegon', 
        'Cimahi', 
        'Cirebon', 
        'Dumai', 
        'Dairi', 
        'Deiyai', 
        'Deli Serdang', 
        'Demak', 
        'Denpasar', 
        'Depok', 
        'Dharmasraya', 
        'Dogiyai', 
        'Dompu', 
        'Donggala', 
        'Empat Lawang', 
        'Ende', 
        'Enrekang', 
        'Fakfak', 
        'Flores Timur', 
        'Garut', 
        'Gayo Lues', 
        'Gianyar', 
        'Gorontalo', 
        'Gorontalo Utara', 
        'Gowa', 
        'Gresik', 
        'Grobogan', 
        'Gunung Kidul', 
        'Gunung Mas', 
        'Gunungsitoli', 
        'Halmahera Barat', 
        'Halmahera Selatan', 
        'Halmahera Tengah', 
        'Halmahera Timur', 
        'Halmahera Utara', 
        'Hulu Sungai Selatan', 
        'Hulu Sungai Tengah', 
        'Hulu Sungai Utara', 
        'Humbang Hasundutan', 
        'Indragiri Hilir', 
        'Indragiri Hulu', 
        'Indramayu', 
        'Intan Jaya', 
        'Jakarta Barat', 
        'Jakarta Pusat', 
        'Jakarta Selatan', 
        'Jakarta Timur', 
        'Jakarta Utara', 
        'Jambi', 
        'Jayapura', 
        'Jayawijaya', 
        'Jember', 
        'Jembrana', 
        'Jeneponto', 
        'Jepara', 
        'Jombang', 
        'Kaimana', 
        'Kampar', 
        'Kapuas', 
        'Kapuas Hulu', 
        'Karang Asem', 
        'Karanganyar', 
        'Karawang', 
        'Karimun', 
        'Karo', 
        'Katingan', 
        'Kaur', 
        'Kayong Utara', 
        'Kebumen', 
        'Kediri', 
        'Keerom', 
        'Kendal', 
        'Kendari', 
        'Kepahiang', 
        'Kepulauan Anambas', 
        'Kepulauan Aru', 
        'Kepulauan Mentawai', 
        'Kepulauan Meranti', 
        'Kepulauan Sangihe', 
        'Kepulauan Selayar', 
        'Kepulauan Seribu', 
        'Kepulauan Sula', 
        'Kepulauan Talaud', 
        'Kepulauan Yapen', 
        'Kerinci', 
        'Ketapang', 
        'Klaten', 
        'Klungkung', 
        'Kolaka', 
        'Kolaka Utara', 
        'Konawe', 
        'Konawe Selatan', 
        'Konawe Utara', 
        'Kotamobagu', 
        'Kotawaringin Barat', 
        'Kotawaringin Timur', 
        'Kuantan Singingi', 
        'Kubu Raya', 
        'Kudus', 
        'Kulon Progo', 
        'Kuningan', 
        'Kupang', 
        'Kutai Barat', 
        'Kutai Kartanegara', 
        'Kutai Timur', 
        'Labuhan Batu', 
        'Labuhan Batu Selatan', 
        'Labuhan Batu Utara', 
        'Lahat', 
        'Lamandau', 
        'Lamongan', 
        'Lampung Barat', 
        'Lampung Selatan', 
        'Lampung Tengah', 
        'Lampung Timur', 
        'Lampung Utara', 
        'Landak', 
        'Langkat', 
        'Langsa', 
        'Lanny Jaya', 
        'Lebak', 
        'Lebong', 
        'Lembata', 
        'Lhokseumawe', 
        'Lima Puluh Kota', 
        'Lingga', 
        'Lombok Barat', 
        'Lombok Tengah', 
        'Lombok Timur', 
        'Lombok Utara', 
        'Lubuklinggau', 
        'Lumajang', 
        'Luwu', 
        'Luwu Timur', 
        'Luwu Utara', 
        'Madiun', 
        'Magelang', 
        'Magetan', 
        'Majalengka', 
        'Majene', 
        'Makassar', 
        'Malang', 
        'Malinau', 
        'Maluku Barat Daya', 
        'Maluku Tengah', 
        'Maluku Tenggara', 
        'Maluku Tenggara Barat', 
        'Mamasa', 
        'Mamberamo Raya', 
        'Mamberamo Tengah', 
        'Mamuju', 
        'Mamuju Utara', 
        'Manado', 
        'Mandailing Natal', 
        'Manggarai', 
        'Manggarai Barat', 
        'Manggarai Timur', 
        'Manokwari', 
        'Mappi', 
        'Maros', 
        'Mataram', 
        'Maybrat', 
        'Medan', 
        'Melawi', 
        'Merangin', 
        'Merauke', 
        'Mesuji', 
        'Metro', 
        'Mimika', 
        'Minahasa', 
        'Minahasa Selatan', 
        'Minahasa Tenggara', 
        'Minahasa Utara', 
        'Mojokerto', 
        'Morowali', 
        'Muara Enim', 
        'Muaro Jambi', 
        'Mukomuko', 
        'Muna', 
        'Murung Raya', 
        'Musi Banyuasin', 
        'Musi Rawas', 
        'Nabire', 
        'Nagan Raya', 
        'Nagekeo', 
        'Natuna', 
        'Nduga', 
        'Ngada', 
        'Nganjuk', 
        'Ngawi', 
        'Nias', 
        'Nias Barat', 
        'Nias Selatan', 
        'Nias Utara', 
        'Nunukan', 
        'Ogan Ilir', 
        'Ogan Komering Ilir', 
        'Ogan Komering Ulu', 
        'Ogan Komering Ulu Selatan', 
        'Ogan Komering Ulu Timur', 
        'Pacitan', 
        'Padang', 
        'Padang Lawas', 
        'Padang Lawas Utara', 
        'Padang Panjang', 
        'Padang Pariaman', 
        'Padangsidimpuan', 
        'Pagar Alam', 
        'Pakpak Bharat', 
        'Palangka Raya', 
        'Palembang', 
        'Palopo', 
        'Palu', 
        'Pamekasan', 
        'Pandeglang', 
        'Pangandaran', 
        'Pangkajene Dan Kepulauan', 
        'Pangkal Pinang', 
        'Paniai', 
        'Parepare', 
        'Pariaman', 
        'Parigi Moutong', 
        'Pasaman', 
        'Pasaman Barat', 
        'Paser', 
        'Pasuruan', 
        'Pati', 
        'Payakumbuh', 
        'Pegunungan Bintang', 
        'Pekalongan', 
        'Pekanbaru', 
        'Pelalawan', 
        'Pemalang', 
        'Pematang Siantar', 
        'Penajam Paser Utara', 
        'Pesawaran', 
        'Pesisir Barat', 
        'Pesisir Selatan', 
        'Pidie', 
        'Pidie Jaya', 
        'Pinrang', 
        'Pohuwato', 
        'Polewali Mandar', 
        'Ponorogo', 
        'Pontianak', 
        'Poso', 
        'Prabumulih', 
        'Pringsewu', 
        'Probolinggo', 
        'Pulang Pisau', 
        'Pulau Morotai', 
        'Puncak', 
        'Puncak Jaya', 
        'Purbalingga', 
        'Purwakarta', 
        'Purworejo', 
        'Raja Ampat', 
        'Rejang Lebong', 
        'Rembang', 
        'Rokan Hilir', 
        'Rokan Hulu', 
        'Rote Ndao', 
        'Siak', 
        'Sabang', 
        'Sabu Raijua', 
        'Salatiga', 
        'Samarinda', 
        'Sambas', 
        'Samosir', 
        'Sampang', 
        'Sanggau', 
        'Sarmi', 
        'Sarolangun', 
        'Sawah Lunto', 
        'Sekadau', 
        'Seluma', 
        'Semarang', 
        'Seram Bagian Barat', 
        'Seram Bagian Timur', 
        'Serang', 
        'Serdang Bedagai', 
        'Seruyan', 
        'Siau Tagulandang Biaro', 
        'Sibolga', 
        'Sidenreng Rappang', 
        'Sidoarjo', 
        'Sigi', 
        'Sijunjung', 
        'Sikka', 
        'Simalungun', 
        'Simeulue', 
        'Singkawang', 
        'Sinjai', 
        'Sintang', 
        'Situbondo', 
        'Sleman', 
        'Solok', 
        'Solok Selatan', 
        'Soppeng', 
        'Sorong', 
        'Sorong Selatan', 
        'Sragen', 
        'Subang', 
        'Subulussalam', 
        'Sukabumi', 
        'Sukamara', 
        'Sukoharjo', 
        'Sumba Barat', 
        'Sumba Barat Daya', 
        'Sumba Tengah', 
        'Sumba Timur', 
        'Sumbawa', 
        'Sumbawa Barat', 
        'Sumedang', 
        'Sumenep', 
        'Sungai Penuh', 
        'Supiori', 
        'Surabaya', 
        'Surakarta', 
        'Tabalong', 
        'Tabanan', 
        'Takalar', 
        'Tambrauw', 
        'Tana Tidung', 
        'Tana Toraja', 
        'Tanah Bumbu', 
        'Tanah Datar', 
        'Tanah Laut', 
        'Tangerang', 
        'Tangerang Selatan', 
        'Tanggamus', 
        'Tanjung Balai', 
        'Tanjung Jabung Barat', 
        'Tanjung Jabung Timur', 
        'Tanjung Pinang', 
        'Tapanuli Selatan', 
        'Tapanuli Tengah', 
        'Tapanuli Utara', 
        'Tapin', 
        'Tarakan', 
        'Tasikmalaya', 
        'Tebing Tinggi', 
        'Tebo', 
        'Tegal', 
        'Teluk Bintuni', 
        'Teluk Wondama', 
        'Temanggung', 
        'Ternate', 
        'Tidore Kepulauan', 
        'Timor Tengah Selatan', 
        'Timor Tengah Utara', 
        'Toba Samosir', 
        'Tojo Una-una', 
        'Toli-toli', 
        'Tolikara', 
        'Tomohon', 
        'Toraja Utara', 
        'Trenggalek', 
        'Tual', 
        'Tuban', 
        'Tulang Bawang Barat', 
        'Tulangbawang', 
        'Tulungagung', 
        'Wajo', 
        'Wakatobi', 
        'Waropen', 
        'Way Kanan', 
        'Wonogiri', 
        'Wonosobo', 
        'Yahukimo', 
        'Yalimo', 
        'Yogyakarta'
    ]
}